#!/bin/bash

system_type=$(uname -s)

config_neovim() {
  rustup default stable
  #npm install neovim # needs to be installed globally
  #cpanm Neovim::Ext # needs to be installed globally
}

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi

  # TODO: Enter a step to install latest xcode version: https://www.freecodecamp.org/news/how-to-download-and-install-xcode/

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    eval "$(/opt/homebrew/bin/brew shellenv)"
    brew bundle --global
  fi

  # TODO: append updated bash to /etc/shells if it doesn't exist
  # sudo echo "/opt/homebrew/bin/bash" >> /etc/shells

else
  echo "Nothing to specific to bootstrap for $(uname -s) system type"
fi

config_neovim
