#!/bin/bash

system_type=$(uname -s)

config_neovim() {
  rustup default stable
  #npm install neovim # needs to be installed globally
  #cpanm Neovim::Ext # needs to be installed globally
}

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

else
  echo "Nothing to specific to bootstrap for $(uname -s) system type"
fi

config_neovim
