return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "css",
      "diff",
      "dockerfile",
      "dot",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "go",
      "gomod",
      "gosum",
      "gowork",
      "graphql",
      "hcl",
      "latex",
      "json",
      "json5",
      "markdown",
      "markdown_inline",
      "norg",
      "scss",
      "svelte",
      "terraform",
      "typst",
      "vue",
      "yaml",
      "lua",
      "python",
      "typescript",
      "tsx",
    },
    highlight = {
      enable = true,
    },
  },
}
