#!/bin/bash

# Only set completions if the jfrog command exists
command -v jfrog >/dev/null 2>&1 || return

_jfrog() {
  local cur opts base
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  opts=$(${COMP_WORDS[@]:0:$COMP_CWORD} --generate-bash-completion)
  COMPREPLY=($(compgen -W "${opts}" -- ${cur}))
}

complete -F _jfrog -o default jfrog
complete -F _jfrog -o default jf
